server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toilet-db?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    devtools:
      livereload:
        enabled: true

logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace